#!/bin/sh

/usr/bin/etmpfiles "$@"

ret=$?
case "$ret" in
    65) exit 0    ;; # EX_DATAERR, some lines errored but no other error
    73) exit 0    ;; # EX_CANTCREAT, valid config but can't be executed
    *)  exit $ret ;; # anything else
esac
